version: "3"

services:
  api_transactions:
    build:
      context: .
    image: api_transactions
    container_name: api_transactions
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: "yarn start"
